import React, { useRef, useState } from 'react';
import styles from './ProjectDetails.module.css';
import svgPaths from '../../../imports/svg-m590sprq1z';

const AlertIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
    <path d={svgPaths.p341e8200} fill="#CE7309" />
  </svg>
);

const DateIcon: React.FC = () => (
  <svg width="18" height="18" viewBox="0 0 18 18" fill="none" className={styles.dateIcon}>
    <path d={svgPaths.p24a05d00} fill="#4A4A4A" />
  </svg>
);

export const ProjectDetails: React.FC = () => {
  const [formData, setFormData] = useState({
    ertmProjectId: 'PRJ-8YV03FK',
    sapProjectId: '',
    projectCodeName: '',
    projectType: '',
    estimatedStartDate: '', // ISO YYYY-MM-DD
    estimatedEndDate: '',
    dataType: '',
    description: '',
  });

  const [charCount, setCharCount] = useState(0);

  const startDateRef = useRef<HTMLInputElement | null>(null);
  const endDateRef = useRef<HTMLInputElement | null>(null);

  const handleTextareaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const text = e.target.value;
    setCharCount(text.length);
    setFormData({ ...formData, description: text });
  };

  function getOrdinal(n: number) {
    const v = n % 100;
    if (v >= 11 && v <= 13) return 'th';
    switch (n % 10) {
      case 1:
        return 'st';
      case 2:
        return 'nd';
      case 3:
        return 'rd';
      default:
        return 'th';
    }
  }

  function formatDate(isoDate: string) {
    if (!isoDate) return '';
    // Append time to avoid timezone shift when constructing Date
    const d = new Date(isoDate + 'T00:00:00');
    if (Number.isNaN(d.getTime())) return '';
    const month = d.toLocaleString('default', { month: 'long' }); // January
    const day = d.getDate();
    const year = d.getFullYear();
    const ordinal = getOrdinal(day);
    return `${month} ${day}${ordinal}, ${year}`;
  }

  const formattedStart = formatDate(formData.estimatedStartDate);
  const formattedEnd = formatDate(formData.estimatedEndDate);

  const openPicker = (ref: React.RefObject<HTMLInputElement>) => {
    if (!ref) return;
    const el = ref.current;
    if (!el) return;
    // showPicker exists in some browsers; fallback to focus+click
    // @ts-ignore
    if (typeof el.showPicker === 'function') {
      // @ts-ignore
      el.showPicker();
    } else {
      el.focus();
      el.click();
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h2 className={styles.title}>Project Details</h2>
        <p className={styles.description}>Define project scope, timeline, and requirements</p>
      </div>

      {/* Row 1: ERTM Project ID, SAP Project ID, Project Code Name */}
      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={`${styles.label} ${styles.labelGray}`}>
            ERTM Project ID <span className={styles.required}>*</span>
          </label>
          <input type="text" className={styles.input} value={formData.ertmProjectId} disabled />
          <p className={`${styles.additionalInfo} ${styles.additionalInfoGray}`}>
            Auto Generated by ServiceNow
          </p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>SAP Project ID</label>
          <select
            className={styles.select}
            value={formData.sapProjectId}
            onChange={(e) => setFormData({ ...formData, sapProjectId: e.target.value })}
          >
            <option value="" hidden></option>
            <option value="SAP-PRJ001">SAP-PRJ001</option>
            <option value="SAP-PRJ002">SAP-PRJ002</option>
            <option value="SAP-PRJ003">SAP-PRJ003</option>
            <option value="SAP-PRJ004">SAP-PRJ004</option>
          </select>
          <p className={styles.additionalInfo}>If unavailable, you may proceed and update later.</p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>
            Project Code Name <span className={styles.required}>*</span>
          </label>
          <select
            className={styles.select}
            value={formData.projectCodeName}
            onChange={(e) => setFormData({ ...formData, projectCodeName: e.target.value })}
          >
            <option value="" hidden></option>
            <option value="PCN-0001">PCN-0001</option>
            <option value="PCN-0002">PCN-0002</option>
            <option value="PCN-0003">PCN-0003</option>
          </select>
          <p className={styles.additionalInfo}>Select a name from the list, or add a new one.</p>
        </div>
      </div>

      {/* Row 2: Project Type, Start Date, End Date */}
      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Project Type</label>
          <select
            className={styles.select}
            value={formData.projectType}
            onChange={(e) => setFormData({ ...formData, projectType: e.target.value })}
          >
            <option value="" hidden></option>
            <option value="internal">Development</option>
            <option value="external">Proof of concept</option>
            <option value="platform">Platform build</option>
          </select>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Estimated Start Date</label>

          {/* Hidden native date input (kept for native picker) */}
          <input
            ref={startDateRef}
            type="date"
            value={formData.estimatedStartDate}
            onChange={(e) => setFormData({ ...formData, estimatedStartDate: e.target.value })}
            // visually hide without changing your CSS file
            style={{
              position: 'absolute',
              width: '1px',
              height: '1px',
              padding: 0,
              margin: '-1px',
              overflow: 'hidden',
              clip: 'rect(0 0 0 0)',
              whiteSpace: 'nowrap',
              border: 0,
            }}
            aria-hidden={false}
          />

          {/* Visible formatted read-only input using your existing dateInput styles */}
          <div className={styles.dateInput} onClick={() => openPicker(startDateRef)} role="button" tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                openPicker(startDateRef);
              }
            }}>
            <DateIcon />
            <input
              type="text"
              readOnly
              value={formattedStart}
              placeholder=""
              className={styles.input}
              style={{ border: 'none', padding: 0, margin: 0, background: 'transparent', color: '#282926', cursor: 'pointer' }}
              aria-label="Estimated start date"
            />
          </div>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Estimated End Date</label>

          {/* Hidden native date input (kept for native picker) */}
          <input
            ref={endDateRef}
            type="date"
            value={formData.estimatedEndDate}
            onChange={(e) => setFormData({ ...formData, estimatedEndDate: e.target.value })}
            style={{
              position: 'absolute',
              width: '1px',
              height: '1px',
              padding: 0,
              margin: '-1px',
              overflow: 'hidden',
              clip: 'rect(0 0 0 0)',
              whiteSpace: 'nowrap',
              border: 0,
            }}
            aria-hidden={false}
          />

          {/* Visible formatted read-only input using your existing dateInput styles */}
          <div className={styles.dateInput} onClick={() => openPicker(endDateRef)} role="button" tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                openPicker(endDateRef);
              }
            }}>
            <DateIcon />
            <input
              type="text"
              readOnly
              value={formattedEnd}
              placeholder=""
              className={styles.input}
              style={{ border: 'none', padding: 0, margin: 0, background: 'transparent', color: '#282926', cursor: 'pointer' }}
              aria-label="Estimated end date"
            />
          </div>
        </div>
      </div>

      {/* Row 3: Data Type */}
      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Personal or Protected Data Involved?</label>
          <select
            className={styles.select}
            value={formData.dataType}
            onChange={(e) => setFormData({ ...formData, dataType: e.target.value })}
          >
            <option value="" hidden></option>
            <option value="yes">Yes</option>
            <option value="no">No</option>
          </select>
        </div>
      </div>

      {/* Textarea */}
      <div className={styles.formGroup}>
        <label className={styles.label}>Project Description</label>
        <div className={styles.textareaWrapper}>
          <textarea
            className={styles.textarea}
            value={formData.description}
            onChange={handleTextareaChange}
            maxLength={80}
          />
          <div className={styles.wordCounter}>{charCount}/80</div>
        </div>
      </div>
    </div>
  );
};